### ISSUE TITLE
在Mac端运行你的项目报错了

### ISSUE THREAD

**Issue by lycfr** [leng-yue/py-scrcpy-client#14]
```
Traceback (most recent call last):
  File "/Users/cfr/PycharmProjects/py-scrcpy-client/scrcpy/core.py", line 184, in __stream_loop
    raw_h264 = self.__video_socket.recv(0x10000)
BlockingIOError: [Errno 35] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cfr/PycharmProjects/py-scrcpy-client/scrcpy_ui/main.py", line 92, in handler
    evt.position().x() / ratio, evt.position().y() / ratio, action
AttributeError: 'QMouseEvent' object has no attribute 'position'
```
看着好像是引入包的时候报错了
![image](https://user-images.githubusercontent.com/29672247/150073725-31994747-6ee2-4589-8532-66507ca503c6.png)

![image](https://user-images.githubusercontent.com/29672247/150073756-d9c61ee6-1253-4eff-a850-787de8cb5216.png)

**Comment by lycfr** [comment]
有办法兼容一下Mac端吗？

**Comment by leng-yue** [comment]
我就是在 mac 开发的, 你能发下你的 `pip freeze` 么.

**Comment by lycfr** [comment]
好像可以了
