### ISSUE TITLE
pyinstaller fatal error

### ISSUE THREAD

**Issue by JustinDBruce** [leng-yue/py-scrcpy-client#6]
Hello,
I am trying to create an exe with this project via pyinstaller, but I am getting an error:
     -Traceback (most recent call last):
  File "main.py", line 8, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "scrcpy\__init__.py", line 6, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "scrcpy\core.py", line 12, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "av\__init__.py", line 9, in <module>
ImportError: DLL load failed while importing _core: The specified procedure could not be found.
[17436] Failed to execute script 'main' due to unhandled exception!

I have been working on it for a couple days now, I believe it is from the av import:
       -from av.codec import CodecContext

Not sure what I am doing wrong, any help would be appreciated.
Thanks!

**Comment by leng-yue** [comment]
This is a pyav related question. After searching on google, I will recommend you to check the FFmpeg dependency.   
Please make sure the directory containing your FFmpeg DLLs is in the PATH.   
Here is pyav's issue page: https://github.com/PyAV-Org/PyAV/issues?q=ImportError%3A+DLL+load+failed
