### ISSUE TITLE
Video stream is disconnected after new update (2h ago)

### ISSUE THREAD

**Issue by uwuv3** [leng-yue/py-scrcpy-client#75]
it returns ['CLASSPATH=/data/local/tmp/scrcpy-server.jar', 'app_process', '/', 'com.genymobile.scrcpy.Server', '2.4', 'log_level=debug', 'max_size=0', 'max_fps=0', 'video_bit_rate=8000000', 'video_encoder=OMX.google.h264.encoder', 'video_codec=h264', 'tunnel_forward=true', 'send_frame_meta=false', 'control=true', 'audio=false', 'show_touches=true', 'stay_awake=false', 'power_off_on_close=false', 'clipboard_autosync=false']
SM-T220
Exception in thread Thread-1 (__stream_loop):
Traceback (most recent call last):
  File "c:\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "c:\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\User1\Desktop\YoloTest\scrcpy\core.py", line 261, in __stream_loop
    raise e
  File "c:\Users\User1\Desktop\YoloTest\scrcpy\core.py", line 242, in __stream_loop
    raise ConnectionError("Video stream is disconnected")

**Comment by uwuv3** [comment]
i will use old version (https://github.com/leng-yue/py-scrcpy-client/commit/b7faddac3fa80b07e2a12077b4522a0262f0f1e2) until it fixes
