### ISSUE TITLE
Xiaomi 15 Pro connection error

### ISSUE THREAD

**Issue by Liziguo** [leng-yue/py-scrcpy-client#86]
`Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "D:\PycharmProjects\phone_controller\.venv\lib\site-packages\scrcpy\core.py", line 253, in __stream_loop
    raise e
  File "D:\PycharmProjects\phone_controller\.venv\lib\site-packages\scrcpy\core.py", line 234, in __stream_loop
    raise ConnectionError("Video stream is disconnected")
ConnectionError: Video stream is disconnected`

**Comment by Liziguo** [comment]
It has been resolved. I originally installed it using "pip install scrcpy-client", but it was an old version. My solution was to simply copy the code to my project.

**Comment by dzhh** [comment]
我之前是澎湃OS1.0是可以的，升级澎湃OS2就报这个错， 需要把最新的代码复制到工程里面。

**Comment by Robinmarsx** [comment]
这是什么问题啊，我想跑py-scrcpy 就会报错，原因好像是安卓15不行， 如果用安卓14就不会报错

**Comment by Robinmarsx** [comment]
怎么把最新的代码复制到工程里，有没有大佬解释下

**Comment by Liziguo** [comment]
> 怎么把最新的代码复制到工程里，有没有大佬解释下

不要使用pip install安装，直接clone源代码, 把源代码下的scrcpy文件夹拷贝到你的项目就可以了

**Comment by Robinmarsx** [comment]
可以，很牛
